CI - Add code sniffer
litespeedtech/lscache_wp pull request #744
Opened 2024-09-16 21:28 UTC by timotei-litespeed

2024-09-17 05:02 UTC, tynanbe requested changes

2024-09-17 08:59 UTC, timotei-litespeed commented on .github/workflows/ci.yml
> +      - run: npm ci
Should I do something here?

2024-09-17 09:03 UTC, timotei-litespeed commented on .github/workflows/ci.yml
> +
Removed

2024-09-17 09:03 UTC, timotei-litespeed commented on .github/workflows/ci.yml
> +      # Initialize Cache Composer
Removed

2024-09-17 09:03 UTC, timotei-litespeed commented on .github/workflows/ci.yml
> +      # Initialize Node.js
Changed to name

2024-09-17 09:03 UTC, timotei-litespeed commented on .prettierrc
>  	"overrides": [
Reverted to previous version

2024-09-17 09:03 UTC, timotei-litespeed commented on composer.json
> +		"sniff-check": "phpcs --standard=./phpcs.xml.dist"
Works and changed

2024-09-17 14:28 UTC, tynanbe commented on .github/workflows/ci.yml
> +      - run: npm ci
```yml
      - run: npm clean-install
```

2024-09-17 14:29 UTC, tynanbe commented on .prettierrc
>  	"overrides": [
The file shouldn't show up at all in https://github.com/litespeedtech/lscache_wp/pull/744/files

2024-09-17 15:35 UTC, timotei-litespeed commented on .github/workflows/ci.yml
> +      - run: npm ci
Changed

2024-09-17 15:35 UTC, timotei-litespeed commented on .prettierrc
>  	"overrides": [
Fixed

2024-09-18 18:00 UTC, merged

2024-09-18 18:40 UTC, timotei-litespeed commented
@szepeviktor  these changes have been applied to the future version of the plugin.
Talking to my colleagues we decided to look into new ways to improve error detection, improve the security and help maintain the plugin easier.
If you're still up for it: what suggestions do you have? Please create a branch from https://github.com/litespeedtech/lscache_wp/tree/v7.0 and add changes into a PR.

Thank you!

2024-09-18 20:23 UTC, szepeviktor commented
> what suggestions do you have?

https://github.com/litespeedtech/lscache_wp/pull/742#issuecomment-2351381229

Please consider choosing a coding standard: PSR, WordPress, custom, a minimal.
This is my custom ruleset: https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

I could add EditorConfig (for Prettier) and syntax error check.

As for static analysis: the plugin should pass PHPStan level 0.